# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SymfonyCli < Formula
  desc "Symfony CLI helps Symfony developers manage projects, from local code to remote infrastructure"
  homepage "https://symfony.com"
  version "5.4.19"
  license "AGPL-3.0"

  depends_on "git" => :optional

  on_macos do
    url "https://github.com/symfony-cli/symfony-cli/releases/download/v5.4.19/symfony-cli_darwin_all.tar.gz"
    sha256 "0355e1ce76110203b20a1413df9a27a8597cef1c11fd3db6cc111d61d16eca7e"

    def install
      bin.install "symfony"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/symfony-cli/symfony-cli/releases/download/v5.4.19/symfony-cli_linux_amd64.tar.gz"
      sha256 "ff79b9a3569099fb990666bfe69a0878bc3ba41745424edc7146e9590cfd0d39"

      def install
        bin.install "symfony"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/symfony-cli/symfony-cli/releases/download/v5.4.19/symfony-cli_linux_arm64.tar.gz"
      sha256 "6d062e54d816980697672a78b0fbc51518af73de7a78eb55ac94dba9d7855ea7"

      def install
        bin.install "symfony"
      end
    end
  end

  service do
    run ["#{bin}/symfony", "local:proxy:start", "--foreground"]
    keep_alive true
  end

  test do
    system "#{bin}/symfony version"
  end
end
