# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SymfonyCli < Formula
  desc "Symfony CLI helps Symfony developers manage projects, from local code to remote infrastructure"
  homepage "https://symfony.com"
  version "5.5.5"
  license "AGPL-3.0"

  depends_on "git" => :optional

  on_macos do
    url "https://github.com/symfony-cli/symfony-cli/releases/download/v5.5.5/symfony-cli_darwin_all.tar.gz"
    sha256 "2529b6e34087ef1914580aa87f8d5b16502fb220c2dc7ed90e974961bebcac48"

    def install
      bin.install "symfony"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/symfony-cli/symfony-cli/releases/download/v5.5.5/symfony-cli_linux_amd64.tar.gz"
      sha256 "77bf016dea7b4e4a3f8f4b10540293f9a8c0bf6200451f63af739c37b44a9548"

      def install
        bin.install "symfony"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/symfony-cli/symfony-cli/releases/download/v5.5.5/symfony-cli_linux_armv6.tar.gz"
      sha256 "97e0f467d8cb8bd6b462bf8af413d862115ac6a73333a534108879d8c3f72e59"

      def install
        bin.install "symfony"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/symfony-cli/symfony-cli/releases/download/v5.5.5/symfony-cli_linux_arm64.tar.gz"
      sha256 "ec606aee848c42be45fb9f30d2f62b1848d0fae22bcf3901af88b57a6cc9572b"

      def install
        bin.install "symfony"
      end
    end
  end

  service do
    run ["#{bin}/symfony", "local:proxy:start", "--foreground"]
    keep_alive true
  end

  test do
    system "#{bin}/symfony version"
  end
end
